// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package github.services;

import github.services.RepositoryCollector;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RepositoryCollector_Roo_Configurable {
    
    declare @type: RepositoryCollector: @Configurable;
    
}
