// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package github.utils.impl;

import github.utils.impl.CommitParserImpl;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CommitParserImpl_Roo_Configurable {
    
    declare @type: CommitParserImpl: @Configurable;
    
}
