// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package github.models;

import github.models.DataCollection;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DataCollection_Roo_Configurable {
    
    declare @type: DataCollection: @Configurable;
    
}
