// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package github.models;

import github.models.RepoInfo;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RepoInfo_Roo_Configurable {
    
    declare @type: RepoInfo: @Configurable;
    
}
