// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package github.application;

import github.application.GithubPusherApplication;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GithubPusherApplication_Roo_Configurable {
    
    declare @type: GithubPusherApplication: @Configurable;
    
}
